require:
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - lib/rspec-openhab-scripting_jars.rb
    - vendor/**/*

Metrics:
  Enabled: false

Lint/RescueException:
  Enabled: false # we need to rescue Java exceptions quite a bit

Naming/FileName:
  Exclude:
    - lib/rspec-openhab-scripting.rb

Performance/Casecmp:
  AutoCorrect: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/BlockDelimiters:
  IgnoredMethods: []
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  AllowedVariables:
   - $ir
   - $rules
   - $se
   - $scriptExtension
   - $things
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/PercentQLiterals:
  EnforcedStyle: upper_case_q
Style/PerlBackrefs:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
