require:
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics:
  Enabled: false

Layout/LineLength:
  Exclude:
    - lib/rspec-openhab-scripting_jars.rb

Naming/FileName:
  Exclude:
    - lib/rspec-openhab-scripting.rb
    - lib/rspec-openhab-scripting_jars.rb

Performance/Casecmp:
  AutoCorrect: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/BlockDelimiters:
  IgnoredMethods: []
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/PercentQLiterals:
  EnforcedStyle: upper_case_q
Style/PerlBackrefs:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
   - lib/rspec-openhab-scripting_jars.rb
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
