# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar'
  require 'org/apiguardian/apiguardian-api/1.1.1/apiguardian-api-1.1.1.jar'
  require 'org/eclipse/xtext/org.eclipse.xtext.util/2.26.0/org.eclipse.xtext.util-2.26.0.jar'
  require 'log4j/log4j/1.2.17/log4j-1.2.17.jar'
  require 'org/osgi/org.osgi.framework/1.8.0/org.osgi.framework-1.8.0.jar'
  require 'com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar'
  require 'aopalliance/aopalliance/1.0/aopalliance-1.0.jar'
  require 'org/eclipse/xtend/org.eclipse.xtend.lib/2.26.0/org.eclipse.xtend.lib-2.26.0.jar'
  require 'tech/uom/lib/uom-lib-common/2.1/uom-lib-common-2.1.jar'
  require 'com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar'
  require 'com/google/guava/guava/30.1-jre/guava-30.1-jre.jar'
  require 'org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar'
  require 'com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar'
  require 'javax/measure/unit-api/2.1.2/unit-api-2.1.2.jar'
  require 'org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.26.0/org.eclipse.xtext.xbase.lib-2.26.0.jar'
  require 'com/google/code/gson/gson/2.8.9/gson-2.8.9.jar'
  require 'org/eclipse/xtext/org.eclipse.xtext/2.26.0/org.eclipse.xtext-2.26.0.jar'
  require 'org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.26.0/org.eclipse.xtend.lib.macro-2.26.0.jar'
  require 'org/eclipse/platform/org.eclipse.osgi/3.16.0/org.eclipse.osgi-3.16.0.jar'
  require 'javax/inject/javax.inject/1/javax.inject-1.jar'
  require 'org/eclipse/emf/org.eclipse.emf.common/2.17.0/org.eclipse.emf.common-2.17.0.jar'
  require 'com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar'
  require 'si/uom/si-units/2.1/si-units-2.1.jar'
  require 'com/google/inject/guice/5.0.1/guice-5.0.1.jar'
  require 'org/eclipse/platform/org.eclipse.equinox.common/3.13.0/org.eclipse.equinox.common-3.13.0.jar'
  require 'org/antlr/antlr-runtime/3.2/antlr-runtime-3.2.jar'
  require 'org/eclipse/emf/org.eclipse.emf.ecore.xmi/2.16.0/org.eclipse.emf.ecore.xmi-2.16.0.jar'
  require 'org/slf4j/slf4j-api/1.7.35/slf4j-api-1.7.35.jar'
  require 'org/slf4j/slf4j-simple/1.7.35/slf4j-simple-1.7.35.jar'
  require 'tech/units/indriya/2.1.3/indriya-2.1.3.jar'
  require 'jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.jar'
  require 'org/eclipse/emf/org.eclipse.emf.ecore/2.20.0/org.eclipse.emf.ecore-2.20.0.jar'
  require 'org/osgi/osgi.cmpn/7.0.0/osgi.cmpn-7.0.0.jar'
  require 'si/uom/si-quantity/2.1/si-quantity-2.1.jar'
end

if defined? Jars
  require_jar 'com.google.code.findbugs', 'jsr305', '3.0.2'
  require_jar 'org.apiguardian', 'apiguardian-api', '1.1.1'
  require_jar 'org.eclipse.xtext', 'org.eclipse.xtext.util', '2.26.0'
  require_jar 'log4j', 'log4j', '1.2.17'
  require_jar 'org.osgi', 'org.osgi.framework', '1.8.0'
  require_jar 'com.google.guava', 'listenablefuture', '9999.0-empty-to-avoid-conflict-with-guava'
  require_jar 'aopalliance', 'aopalliance', '1.0'
  require_jar 'org.eclipse.xtend', 'org.eclipse.xtend.lib', '2.26.0'
  require_jar 'tech.uom.lib', 'uom-lib-common', '2.1'
  require_jar 'com.google.errorprone', 'error_prone_annotations', '2.3.4'
  require_jar 'com.google.guava', 'guava', '30.1-jre'
  require_jar 'org.checkerframework', 'checker-qual', '3.5.0'
  require_jar 'com.google.j2objc', 'j2objc-annotations', '1.3'
  require_jar 'javax.measure', 'unit-api', '2.1.2'
  require_jar 'org.eclipse.xtext', 'org.eclipse.xtext.xbase.lib', '2.26.0'
  require_jar 'com.google.code.gson', 'gson', '2.8.9'
  require_jar 'org.eclipse.xtext', 'org.eclipse.xtext', '2.26.0'
  require_jar 'org.eclipse.xtend', 'org.eclipse.xtend.lib.macro', '2.26.0'
  require_jar 'org.eclipse.platform', 'org.eclipse.osgi', '3.16.0'
  require_jar 'javax.inject', 'javax.inject', '1'
  require_jar 'org.eclipse.emf', 'org.eclipse.emf.common', '2.17.0'
  require_jar 'com.google.guava', 'failureaccess', '1.0.1'
  require_jar 'si.uom', 'si-units', '2.1'
  require_jar 'com.google.inject', 'guice', '5.0.1'
  require_jar 'org.eclipse.platform', 'org.eclipse.equinox.common', '3.13.0'
  require_jar 'org.antlr', 'antlr-runtime', '3.2'
  require_jar 'org.eclipse.emf', 'org.eclipse.emf.ecore.xmi', '2.16.0'
  require_jar 'org.slf4j', 'slf4j-api', '1.7.35'
  require_jar 'org.slf4j', 'slf4j-simple', '1.7.35'
  require_jar 'tech.units', 'indriya', '2.1.3'
  require_jar 'jakarta.annotation', 'jakarta.annotation-api', '1.3.4'
  require_jar 'org.eclipse.emf', 'org.eclipse.emf.ecore', '2.20.0'
  require_jar 'org.osgi', 'osgi.cmpn', '7.0.0'
  require_jar 'si.uom', 'si-quantity', '2.1'
end
